/**
 * Generated by scripts/gen-params-from-cache.ts — do not hand-edit.
 *
 * Bulk parameter registry harvested from AM4-Edit's metadata cache
 * (effectDefinitions_15_2p0.cache, parsed by scripts/parse-cache.ts).
 * Names come from src/protocol/paramNames.ts; add a name there and
 * regenerate to expand coverage. Out-of-band params (channel /
 * level / other pidHighs without a cache record) stay hand-authored
 * in params.ts.
 *
 * Verification: scripts/verify-cache-params.ts confirms every entry
 * here matches the corresponding hand-authored KNOWN_PARAMS entry
 * byte-for-byte (same pidLow/pidHigh, same unit, same displayMin/
 * displayMax). Preflight runs this verification.
 */
import type { Param } from './params.js';

import {
  AMP_TYPES_VALUES,
  CHORUS_TYPES_VALUES,
  COMPRESSOR_TYPES_VALUES,
  DELAY_TYPES_VALUES,
  DRIVE_TYPES_VALUES,
  ENHANCER_TYPES_VALUES,
  FILTER_TYPES_VALUES,
  FLANGER_TYPES_VALUES,
  GATE_TYPES_VALUES,
  GEQ_TYPES_VALUES,
  PHASER_TYPES_VALUES,
  REVERB_TYPES_VALUES,
  TREMOLO_TYPES_VALUES,
  VOLPAN_MODES_VALUES,
  WAH_TYPES_VALUES,
} from './cacheEnums.js';

export const CACHE_PARAMS = {
  'amp.balance': {
    block: 'amp', name: 'balance',
    pidLow: 0x003a, pidHigh: 0x0002,
    unit: 'bipolar_percent', displayMin: -100, displayMax: 100,
  },
  'amp.out_boost_level': {
    block: 'amp', name: 'out_boost_level',
    pidLow: 0x003a, pidHigh: 0x0008,
    unit: 'db', displayMin: 0, displayMax: 4,
  },
  'amp.type': {
    block: 'amp', name: 'type',
    pidLow: 0x003a, pidHigh: 0x000a,
    unit: 'enum', displayMin: 0, displayMax: 247,
    enumValues: AMP_TYPES_VALUES,
  },
  'amp.gain': {
    block: 'amp', name: 'gain',
    pidLow: 0x003a, pidHigh: 0x000b,
    unit: 'knob_0_10', displayMin: 0, displayMax: 10,
  },
  'amp.bass': {
    block: 'amp', name: 'bass',
    pidLow: 0x003a, pidHigh: 0x000c,
    unit: 'knob_0_10', displayMin: 0, displayMax: 10,
  },
  'amp.mid': {
    block: 'amp', name: 'mid',
    pidLow: 0x003a, pidHigh: 0x000d,
    unit: 'knob_0_10', displayMin: 0, displayMax: 10,
  },
  'amp.treble': {
    block: 'amp', name: 'treble',
    pidLow: 0x003a, pidHigh: 0x000e,
    unit: 'knob_0_10', displayMin: 0, displayMax: 10,
  },
  'amp.master': {
    block: 'amp', name: 'master',
    pidLow: 0x003a, pidHigh: 0x000f,
    unit: 'knob_0_10', displayMin: 0, displayMax: 10,
  },
  'amp.depth': {
    block: 'amp', name: 'depth',
    pidLow: 0x003a, pidHigh: 0x001a,
    unit: 'knob_0_10', displayMin: 0, displayMax: 10,
  },
  'amp.presence': {
    block: 'amp', name: 'presence',
    pidLow: 0x003a, pidHigh: 0x001e,
    unit: 'knob_0_10', displayMin: 0, displayMax: 10,
  },
  'drive.balance': {
    block: 'drive', name: 'balance',
    pidLow: 0x0076, pidHigh: 0x0002,
    unit: 'bipolar_percent', displayMin: -100, displayMax: 100,
  },
  'drive.type': {
    block: 'drive', name: 'type',
    pidLow: 0x0076, pidHigh: 0x000a,
    unit: 'enum', displayMin: 0, displayMax: 77,
    enumValues: DRIVE_TYPES_VALUES,
  },
  'drive.drive': {
    block: 'drive', name: 'drive',
    pidLow: 0x0076, pidHigh: 0x000b,
    unit: 'knob_0_10', displayMin: 0, displayMax: 10,
  },
  'drive.tone': {
    block: 'drive', name: 'tone',
    pidLow: 0x0076, pidHigh: 0x000c,
    unit: 'knob_0_10', displayMin: 0, displayMax: 10,
  },
  'drive.level': {
    block: 'drive', name: 'level',
    pidLow: 0x0076, pidHigh: 0x000d,
    unit: 'knob_0_10', displayMin: 0, displayMax: 10,
  },
  'drive.mix': {
    block: 'drive', name: 'mix',
    pidLow: 0x0076, pidHigh: 0x000e,
    unit: 'percent', displayMin: 0, displayMax: 100,
  },
  'reverb.mix': {
    block: 'reverb', name: 'mix',
    pidLow: 0x0042, pidHigh: 0x0001,
    unit: 'percent', displayMin: 0, displayMax: 100,
  },
  'reverb.balance': {
    block: 'reverb', name: 'balance',
    pidLow: 0x0042, pidHigh: 0x0002,
    unit: 'bipolar_percent', displayMin: -100, displayMax: 100,
  },
  'reverb.type': {
    block: 'reverb', name: 'type',
    pidLow: 0x0042, pidHigh: 0x000a,
    unit: 'enum', displayMin: 0, displayMax: 78,
    enumValues: REVERB_TYPES_VALUES,
  },
  'reverb.time': {
    block: 'reverb', name: 'time',
    pidLow: 0x0042, pidHigh: 0x000b,
    unit: 'seconds', displayMin: 0.1, displayMax: 100,
  },
  'reverb.size': {
    block: 'reverb', name: 'size',
    pidLow: 0x0042, pidHigh: 0x000f,
    unit: 'percent', displayMin: 0, displayMax: 100,
  },
  'reverb.predelay': {
    block: 'reverb', name: 'predelay',
    pidLow: 0x0042, pidHigh: 0x0010,
    unit: 'ms', displayMin: 0, displayMax: 250,
  },
  'reverb.springs': {
    block: 'reverb', name: 'springs',
    pidLow: 0x0042, pidHigh: 0x001b,
    unit: 'count', displayMin: 2, displayMax: 6,
  },
  'reverb.spring_tone': {
    block: 'reverb', name: 'spring_tone',
    pidLow: 0x0042, pidHigh: 0x001c,
    unit: 'knob_0_10', displayMin: 0, displayMax: 10,
  },
  'delay.mix': {
    block: 'delay', name: 'mix',
    pidLow: 0x0046, pidHigh: 0x0001,
    unit: 'percent', displayMin: 0, displayMax: 100,
  },
  'delay.balance': {
    block: 'delay', name: 'balance',
    pidLow: 0x0046, pidHigh: 0x0002,
    unit: 'bipolar_percent', displayMin: -100, displayMax: 100,
  },
  'delay.type': {
    block: 'delay', name: 'type',
    pidLow: 0x0046, pidHigh: 0x000a,
    unit: 'enum', displayMin: 0, displayMax: 28,
    enumValues: DELAY_TYPES_VALUES,
  },
  'delay.time': {
    block: 'delay', name: 'time',
    pidLow: 0x0046, pidHigh: 0x000c,
    unit: 'ms', displayMin: 0, displayMax: 8000,
  },
  'delay.feedback': {
    block: 'delay', name: 'feedback',
    pidLow: 0x0046, pidHigh: 0x000e,
    unit: 'bipolar_percent', displayMin: -100, displayMax: 100,
  },
  'chorus.mix': {
    block: 'chorus', name: 'mix',
    pidLow: 0x004e, pidHigh: 0x0001,
    unit: 'percent', displayMin: 0, displayMax: 100,
  },
  'chorus.balance': {
    block: 'chorus', name: 'balance',
    pidLow: 0x004e, pidHigh: 0x0002,
    unit: 'bipolar_percent', displayMin: -100, displayMax: 100,
  },
  'chorus.type': {
    block: 'chorus', name: 'type',
    pidLow: 0x004e, pidHigh: 0x000a,
    unit: 'enum', displayMin: 0, displayMax: 19,
    enumValues: CHORUS_TYPES_VALUES,
  },
  'chorus.rate': {
    block: 'chorus', name: 'rate',
    pidLow: 0x004e, pidHigh: 0x000c,
    unit: 'hz', displayMin: 0.1, displayMax: 10,
  },
  'chorus.depth': {
    block: 'chorus', name: 'depth',
    pidLow: 0x004e, pidHigh: 0x000e,
    unit: 'percent', displayMin: 0, displayMax: 100,
  },
  'flanger.mix': {
    block: 'flanger', name: 'mix',
    pidLow: 0x0052, pidHigh: 0x0001,
    unit: 'percent', displayMin: 0, displayMax: 100,
  },
  'flanger.balance': {
    block: 'flanger', name: 'balance',
    pidLow: 0x0052, pidHigh: 0x0002,
    unit: 'bipolar_percent', displayMin: -100, displayMax: 100,
  },
  'flanger.type': {
    block: 'flanger', name: 'type',
    pidLow: 0x0052, pidHigh: 0x000a,
    unit: 'enum', displayMin: 0, displayMax: 31,
    enumValues: FLANGER_TYPES_VALUES,
  },
  'flanger.rate': {
    block: 'flanger', name: 'rate',
    pidLow: 0x0052, pidHigh: 0x000b,
    unit: 'hz', displayMin: 0.05, displayMax: 10,
  },
  'flanger.depth': {
    block: 'flanger', name: 'depth',
    pidLow: 0x0052, pidHigh: 0x000d,
    unit: 'percent', displayMin: 0, displayMax: 100,
  },
  'flanger.feedback': {
    block: 'flanger', name: 'feedback',
    pidLow: 0x0052, pidHigh: 0x000e,
    unit: 'bipolar_percent', displayMin: -99, displayMax: 99,
  },
  'phaser.mix': {
    block: 'phaser', name: 'mix',
    pidLow: 0x005a, pidHigh: 0x0001,
    unit: 'percent', displayMin: 0, displayMax: 100,
  },
  'phaser.balance': {
    block: 'phaser', name: 'balance',
    pidLow: 0x005a, pidHigh: 0x0002,
    unit: 'bipolar_percent', displayMin: -100, displayMax: 100,
  },
  'phaser.type': {
    block: 'phaser', name: 'type',
    pidLow: 0x005a, pidHigh: 0x000a,
    unit: 'enum', displayMin: 0, displayMax: 16,
    enumValues: PHASER_TYPES_VALUES,
  },
  'phaser.rate': {
    block: 'phaser', name: 'rate',
    pidLow: 0x005a, pidHigh: 0x000c,
    unit: 'hz', displayMin: 0.1, displayMax: 10,
  },
  'phaser.feedback': {
    block: 'phaser', name: 'feedback',
    pidLow: 0x005a, pidHigh: 0x0010,
    unit: 'bipolar_percent', displayMin: -90, displayMax: 90,
  },
  'wah.balance': {
    block: 'wah', name: 'balance',
    pidLow: 0x005e, pidHigh: 0x0002,
    unit: 'bipolar_percent', displayMin: -100, displayMax: 100,
  },
  'wah.type': {
    block: 'wah', name: 'type',
    pidLow: 0x005e, pidHigh: 0x000a,
    unit: 'enum', displayMin: 0, displayMax: 8,
    enumValues: WAH_TYPES_VALUES,
  },
  'compressor.mix': {
    block: 'compressor', name: 'mix',
    pidLow: 0x002e, pidHigh: 0x0001,
    unit: 'percent', displayMin: 0, displayMax: 100,
  },
  'compressor.balance': {
    block: 'compressor', name: 'balance',
    pidLow: 0x002e, pidHigh: 0x0002,
    unit: 'bipolar_percent', displayMin: -100, displayMax: 100,
  },
  'compressor.type': {
    block: 'compressor', name: 'type',
    pidLow: 0x002e, pidHigh: 0x0013,
    unit: 'enum', displayMin: 0, displayMax: 18,
    enumValues: COMPRESSOR_TYPES_VALUES,
  },
  'geq.balance': {
    block: 'geq', name: 'balance',
    pidLow: 0x0032, pidHigh: 0x0002,
    unit: 'bipolar_percent', displayMin: -100, displayMax: 100,
  },
  'geq.type': {
    block: 'geq', name: 'type',
    pidLow: 0x0032, pidHigh: 0x0014,
    unit: 'enum', displayMin: 0, displayMax: 17,
    enumValues: GEQ_TYPES_VALUES,
  },
  'filter.mix': {
    block: 'filter', name: 'mix',
    pidLow: 0x0072, pidHigh: 0x0001,
    unit: 'percent', displayMin: 0, displayMax: 100,
  },
  'filter.balance': {
    block: 'filter', name: 'balance',
    pidLow: 0x0072, pidHigh: 0x0002,
    unit: 'bipolar_percent', displayMin: -100, displayMax: 100,
  },
  'filter.type': {
    block: 'filter', name: 'type',
    pidLow: 0x0072, pidHigh: 0x000a,
    unit: 'enum', displayMin: 0, displayMax: 17,
    enumValues: FILTER_TYPES_VALUES,
  },
  'filter.freq': {
    block: 'filter', name: 'freq',
    pidLow: 0x0072, pidHigh: 0x000b,
    unit: 'hz', displayMin: 20, displayMax: 20000,
  },
  'tremolo.mix': {
    block: 'tremolo', name: 'mix',
    pidLow: 0x006a, pidHigh: 0x0001,
    unit: 'percent', displayMin: 0, displayMax: 100,
  },
  'tremolo.balance': {
    block: 'tremolo', name: 'balance',
    pidLow: 0x006a, pidHigh: 0x0002,
    unit: 'bipolar_percent', displayMin: -100, displayMax: 100,
  },
  'tremolo.type': {
    block: 'tremolo', name: 'type',
    pidLow: 0x006a, pidHigh: 0x000a,
    unit: 'enum', displayMin: 0, displayMax: 6,
    enumValues: TREMOLO_TYPES_VALUES,
  },
  'tremolo.rate': {
    block: 'tremolo', name: 'rate',
    pidLow: 0x006a, pidHigh: 0x000c,
    unit: 'hz', displayMin: 0.2, displayMax: 20,
  },
  'tremolo.depth': {
    block: 'tremolo', name: 'depth',
    pidLow: 0x006a, pidHigh: 0x000d,
    unit: 'percent', displayMin: 0, displayMax: 100,
  },
  'enhancer.mix': {
    block: 'enhancer', name: 'mix',
    pidLow: 0x007a, pidHigh: 0x0001,
    unit: 'percent', displayMin: 0, displayMax: 100,
  },
  'enhancer.balance': {
    block: 'enhancer', name: 'balance',
    pidLow: 0x007a, pidHigh: 0x0002,
    unit: 'bipolar_percent', displayMin: -100, displayMax: 100,
  },
  'enhancer.type': {
    block: 'enhancer', name: 'type',
    pidLow: 0x007a, pidHigh: 0x000e,
    unit: 'enum', displayMin: 0, displayMax: 2,
    enumValues: ENHANCER_TYPES_VALUES,
  },
  'gate.balance': {
    block: 'gate', name: 'balance',
    pidLow: 0x0092, pidHigh: 0x0002,
    unit: 'bipolar_percent', displayMin: -100, displayMax: 100,
  },
  'gate.type': {
    block: 'gate', name: 'type',
    pidLow: 0x0092, pidHigh: 0x0013,
    unit: 'enum', displayMin: 0, displayMax: 3,
    enumValues: GATE_TYPES_VALUES,
  },
  'volpan.balance': {
    block: 'volpan', name: 'balance',
    pidLow: 0x0066, pidHigh: 0x0002,
    unit: 'bipolar_percent', displayMin: -100, displayMax: 100,
  },
  'volpan.mode': {
    block: 'volpan', name: 'mode',
    pidLow: 0x0066, pidHigh: 0x000f,
    unit: 'enum', displayMin: 0, displayMax: 1,
    enumValues: VOLPAN_MODES_VALUES,
  },
} as const satisfies Record<string, Param>;

export type CacheParamKey = keyof typeof CACHE_PARAMS;
