/**
 * Emit `src/protocol/cacheEnums.ts` — the 4 top-level effect type
 * dictionaries pulled from the parsed cache. These are the dropdown
 * lists AM4-Edit shows under Amp Type / Drive Type / Reverb Type /
 * Delay Type, in the exact order the firmware enumerates them.
 *
 * Wire index == array index. Pass the index (as float32) to SET_PARAM
 * at the block's Type pidHigh (all id=10 == pidHigh=0x000A).
 *
 * Also emit `docs/CACHE-DUMP.md` — human-readable listing of every
 * param record for the 4 mapped blocks, so the catalog is visible
 * without loading JSON.
 *
 * Run after `npx tsx scripts/parse-cache.ts`:
 *   npx tsx scripts/gen-cache-enums.ts
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

interface CacheRec {
  offset: number;
  block: number;
  id: number;
  typecode: number;
  kind: 'float' | 'enum' | 'blockHeader';
  a?: number; b?: number; c?: number; d?: number;
  values?: string[];
}

const DECODED_DIR = 'samples/captured/decoded';
const s2: CacheRec[] = JSON.parse(readFileSync(join(DECODED_DIR, 'cache-section2.json'), 'utf8'));
const s3: CacheRec[] = JSON.parse(readFileSync(join(DECODED_DIR, 'cache-section3.json'), 'utf8')).records;

interface BlockLoc {
  label: string;
  constName: string;
  section: 'S2' | 'S3';
  block: number;
  recs: CacheRec[];
  pidLow: number;
}

const BLOCKS: BlockLoc[] = [
  { label: 'Amp',    constName: 'AMP_TYPES',    section: 'S2', block: 5, recs: s2, pidLow: 0x3a },
  { label: 'Drive',  constName: 'DRIVE_TYPES',  section: 'S3', block: 9, recs: s3, pidLow: 0x76 },
  { label: 'Reverb', constName: 'REVERB_TYPES', section: 'S3', block: 0, recs: s3, pidLow: 0x42 },
  { label: 'Delay',  constName: 'DELAY_TYPES',  section: 'S3', block: 1, recs: s3, pidLow: 0x46 },
];

const TYPE_PID_HIGH = 10; // id=10 → pidHigh=0x000A for all 4 main blocks

function paramsOf(loc: BlockLoc): CacheRec[] {
  return loc.recs.filter((r) => r.block === loc.block && r.kind !== 'blockHeader').sort((a, b) => a.id - b.id);
}

function typeEnum(loc: BlockLoc): string[] {
  const rec = paramsOf(loc).find((r) => r.id === TYPE_PID_HIGH && r.kind === 'enum');
  if (!rec) throw new Error(`${loc.label}: no enum at id=${TYPE_PID_HIGH}`);
  return rec.values!;
}

// -- cacheEnums.ts --

function formatTsArray(name: string, values: string[]): string {
  const escaped = values.map((v) => JSON.stringify(v));
  return `export const ${name}: readonly string[] = [\n  ${escaped.join(',\n  ')},\n] as const;`;
}

function toEnumValuesObject(varName: string, values: string[]): string {
  // Emit `Object.fromEntries(values.map((s, i) => [i, s]))` style so
  // params.ts can import one array and use it as `enumValues`.
  return `export const ${varName}: Record<number, string> = Object.fromEntries(${varName.replace(/_VALUES$/, '')}.map((s, i) => [i, s] as const));`;
}

const header = `/**
 * Generated by scripts/gen-cache-enums.ts — do not hand-edit.
 *
 * Source: AM4-Edit metadata cache (effectDefinitions_15_2p0.cache),
 * parsed by scripts/parse-cache.ts, verified against wire captures
 * by scripts/map-cache-params.ts (Session 15).
 *
 * Each array lists the firmware's effect-type dictionary in wire
 * order. The wire value sent in SET_PARAM (at pidHigh=0x000A of the
 * block's pidLow) is the integer index encoded as a float32.
 */
`;

const arrays = BLOCKS.map((b) => formatTsArray(b.constName, typeEnum(b))).join('\n\n');
const mapsSection = BLOCKS.map((b) => toEnumValuesObject(`${b.constName}_VALUES`, typeEnum(b))).join('\n');

const ts = `${header}\n${arrays}\n\n${mapsSection}\n`;
const outPath = 'src/protocol/cacheEnums.ts';
writeFileSync(outPath, ts);
console.log(`wrote ${outPath}`);
for (const b of BLOCKS) {
  console.log(`  ${b.constName}: ${typeEnum(b).length} entries`);
}

// -- docs/CACHE-DUMP.md --

function describeRec(r: CacheRec): string {
  if (r.kind === 'enum') {
    const preview = r.values!.length <= 6
      ? r.values!.map((v) => `\`${v}\``).join(', ')
      : `\`${r.values![0]}\`, \`${r.values![1]}\`, …, \`${r.values![r.values!.length - 1]}\` *(${r.values!.length} total)*`;
    return `enum × ${r.values!.length} — ${preview}`;
  }
  return `float — min=${r.a}, max=${r.b}, display-scale=${r.c}, step=${r.d}`;
}

const md: string[] = [];
md.push('# Cache Dump — mapped blocks');
md.push('');
md.push('Human-readable view of every parameter record in the 4 main effect');
md.push('blocks, extracted from AM4-Edit\'s metadata cache. Generated by');
md.push('`scripts/gen-cache-enums.ts` — do not hand-edit. Regenerate after');
md.push('any change to the cache by running:');
md.push('');
md.push('```');
md.push('npx tsx scripts/parse-cache.ts');
md.push('npx tsx scripts/gen-cache-enums.ts');
md.push('```');
md.push('');
md.push('**Wire protocol:** cache record `id` == wire `pidHigh`. The block\'s');
md.push('`pidLow` is in the section header below. Send SET_PARAM with');
md.push('`(pidLow, pidHigh=id)` and the value encoded per the unit convention');
md.push('in `src/protocol/params.ts`.');
md.push('');
md.push('Parameter *names* are not in the cache — only IDs. Entries whose');
md.push('name is known via wire capture are tagged in `params.ts`. Everything');
md.push('else here is "cache-derived, unnamed" and needs either an AM4-Edit');
md.push('capture or a manual review to label.');
md.push('');

for (const b of BLOCKS) {
  const recs = paramsOf(b);
  const enums = recs.filter((r) => r.kind === 'enum').length;
  const floats = recs.filter((r) => r.kind === 'float').length;
  md.push(`## ${b.label} — pidLow = 0x${b.pidLow.toString(16).padStart(2, '0')}`);
  md.push('');
  md.push(`Cache location: ${b.section} block ${b.block}. ${recs.length} records (${enums} enums, ${floats} floats).`);
  md.push('');
  md.push('| pidHigh | kind | details |');
  md.push('|--------:|------|---------|');
  for (const r of recs) {
    md.push(`| \`0x${r.id.toString(16).padStart(4, '0')}\` | ${r.kind} | ${describeRec(r)} |`);
  }
  md.push('');
}

const mdPath = 'docs/CACHE-DUMP.md';
writeFileSync(mdPath, md.join('\n'));
console.log(`wrote ${mdPath}`);
